name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      # matrix:
      #   python-version: [3.7]

    steps:
    - name: Python Pytest Github Action
      uses: fylein/python-pytest-github-action@v2
